// AUTO-GENERATED by sync-contract/scripts/generate.mjs
// Do NOT hand-edit. Source: sync-contract/schemas/mutation-types.json
// Regenerate with: cd sync-contract && npm run generate
// Last source version: 1.0.0 (2026-04-30)


export const SYNC_MUTATION_TYPES = [
  "create_farm",
  "create_plot",
  "create_crop_cycle",
  "create_daily_log",
  "add_log_task",
  "verify_log",
  "verify_log_v2",
  "add_cost_entry",
  "correct_cost_entry",
  "allocate_global_expense",
  "set_price_config",
  "create_attachment",
  "add_location",
  "schedule.publish",
  "schedule.edit",
  "schedule.clone",
  "plan.add",
  "plan.override",
  "plan.remove",
  "adopt_schedule",
  "migrate_schedule",
  "abandon_schedule",
  "compliance.acknowledge",
  "compliance.resolve",
  "testinstance.collected",
  "testinstance.reported",
  "jobcard.create",
  "jobcard.assign",
  "jobcard.start",
  "jobcard.complete",
  "jobcard.settle",
  "jobcard.cancel",
] as const;

export type SyncMutationType = typeof SYNC_MUTATION_TYPES[number];

export const SYNC_MUTATION_SET: ReadonlySet<SyncMutationType> = new Set(SYNC_MUTATION_TYPES);

export interface SyncMutationDescriptor {
  readonly name: SyncMutationType;
  readonly ownerAggregate: string;
  readonly sinceVersion: string;
  readonly payloadSchema: string;
  readonly deprecatedBy?: SyncMutationType;
}

export const SYNC_MUTATION_CATALOG: Readonly<Record<SyncMutationType, SyncMutationDescriptor>> = Object.freeze({
  "create_farm": { name: "create_farm", ownerAggregate: "Farm", sinceVersion: "0.1.0", payloadSchema: "CreateFarm" },
  "create_plot": { name: "create_plot", ownerAggregate: "Plot", sinceVersion: "0.1.0", payloadSchema: "CreatePlot" },
  "create_crop_cycle": { name: "create_crop_cycle", ownerAggregate: "CropCycle", sinceVersion: "0.1.0", payloadSchema: "CreateCropCycle" },
  "create_daily_log": { name: "create_daily_log", ownerAggregate: "DailyLog", sinceVersion: "0.1.0", payloadSchema: "CreateDailyLog" },
  "add_log_task": { name: "add_log_task", ownerAggregate: "DailyLog", sinceVersion: "0.1.0", payloadSchema: "AddLogTask" },
  "verify_log": { name: "verify_log", ownerAggregate: "DailyLog", sinceVersion: "0.1.0", payloadSchema: "VerifyLog", deprecatedBy: "verify_log_v2" },
  "verify_log_v2": { name: "verify_log_v2", ownerAggregate: "DailyLog", sinceVersion: "0.7.0", payloadSchema: "VerifyLogV2" },
  "add_cost_entry": { name: "add_cost_entry", ownerAggregate: "CostEntry", sinceVersion: "0.2.0", payloadSchema: "AddCostEntry" },
  "correct_cost_entry": { name: "correct_cost_entry", ownerAggregate: "CostEntry", sinceVersion: "0.5.0", payloadSchema: "CorrectCostEntry" },
  "allocate_global_expense": { name: "allocate_global_expense", ownerAggregate: "CostEntry", sinceVersion: "0.5.0", payloadSchema: "AllocateGlobalExpense" },
  "set_price_config": { name: "set_price_config", ownerAggregate: "PriceConfig", sinceVersion: "0.6.0", payloadSchema: "SetPriceConfig" },
  "create_attachment": { name: "create_attachment", ownerAggregate: "Attachment", sinceVersion: "0.4.0", payloadSchema: "CreateAttachment" },
  "add_location": { name: "add_location", ownerAggregate: "DailyLog", sinceVersion: "0.6.0", payloadSchema: "AddLocation" },
  "schedule.publish": { name: "schedule.publish", ownerAggregate: "ScheduleTemplate", sinceVersion: "0.8.0", payloadSchema: "PublishSchedule" },
  "schedule.edit": { name: "schedule.edit", ownerAggregate: "ScheduleTemplate", sinceVersion: "0.8.0", payloadSchema: "EditSchedule" },
  "schedule.clone": { name: "schedule.clone", ownerAggregate: "ScheduleTemplate", sinceVersion: "0.8.0", payloadSchema: "CloneSchedule" },
  "plan.add": { name: "plan.add", ownerAggregate: "PlannedActivity", sinceVersion: "0.8.0", payloadSchema: "AddPlanned" },
  "plan.override": { name: "plan.override", ownerAggregate: "PlannedActivity", sinceVersion: "0.8.0", payloadSchema: "OverridePlanned" },
  "plan.remove": { name: "plan.remove", ownerAggregate: "PlannedActivity", sinceVersion: "0.8.0", payloadSchema: "RemovePlanned" },
  "adopt_schedule": { name: "adopt_schedule", ownerAggregate: "PlannedActivity", sinceVersion: "0.9.0", payloadSchema: "AdoptSchedule" },
  "migrate_schedule": { name: "migrate_schedule", ownerAggregate: "PlannedActivity", sinceVersion: "0.9.0", payloadSchema: "MigrateSchedule" },
  "abandon_schedule": { name: "abandon_schedule", ownerAggregate: "PlannedActivity", sinceVersion: "0.9.0", payloadSchema: "AbandonSchedule" },
  "compliance.acknowledge": { name: "compliance.acknowledge", ownerAggregate: "ComplianceSignal", sinceVersion: "0.9.0", payloadSchema: "ComplianceAcknowledge" },
  "compliance.resolve": { name: "compliance.resolve", ownerAggregate: "ComplianceSignal", sinceVersion: "0.9.0", payloadSchema: "ComplianceResolve" },
  "testinstance.collected": { name: "testinstance.collected", ownerAggregate: "TestInstance", sinceVersion: "0.9.0", payloadSchema: "TestInstanceCollected" },
  "testinstance.reported": { name: "testinstance.reported", ownerAggregate: "TestInstance", sinceVersion: "0.9.0", payloadSchema: "TestInstanceReported" },
  "jobcard.create": { name: "jobcard.create", ownerAggregate: "JobCard", sinceVersion: "1.0.0", payloadSchema: "JobCardCreate" },
  "jobcard.assign": { name: "jobcard.assign", ownerAggregate: "JobCard", sinceVersion: "1.0.0", payloadSchema: "JobCardAssign" },
  "jobcard.start": { name: "jobcard.start", ownerAggregate: "JobCard", sinceVersion: "1.0.0", payloadSchema: "JobCardStart" },
  "jobcard.complete": { name: "jobcard.complete", ownerAggregate: "JobCard", sinceVersion: "1.0.0", payloadSchema: "JobCardComplete" },
  "jobcard.settle": { name: "jobcard.settle", ownerAggregate: "JobCard", sinceVersion: "1.0.0", payloadSchema: "JobCardSettle" },
  "jobcard.cancel": { name: "jobcard.cancel", ownerAggregate: "JobCard", sinceVersion: "1.0.0", payloadSchema: "JobCardCancel" },
});

export function isSyncMutationType(value: string): value is SyncMutationType {
  return SYNC_MUTATION_SET.has(value as SyncMutationType);
}
