// <auto-generated />
using System;
using Accounts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accounts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccountsDbContext))]
    [Migration("20260420052827_AddAffiliationTables")]
    partial class AddAffiliationTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("accounts")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accounts.Domain.Affiliation.BenefitLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BenefitType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("benefit_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SourceGrowthEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_growth_event_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StatusChangedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("status_changed_at_utc");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("benefit_ledger_entries", "accounts");
                });

            modelBuilder.Entity("Accounts.Domain.Affiliation.GrowthEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ux_growth_events_type_reference");

                    b.ToTable("growth_events", "accounts");
                });

            modelBuilder.Entity("Accounts.Domain.Affiliation.ReferralCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_referral_codes_active_code")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("OwnerAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_referral_codes_owner_active")
                        .HasFilter("is_active = TRUE");

                    b.ToTable("referral_codes", "accounts");
                });

            modelBuilder.Entity("Accounts.Domain.Affiliation.ReferralRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("QualifiedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("qualified_at_utc");

                    b.Property<Guid>("ReferralCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("referral_code_id");

                    b.Property<Guid>("ReferredOwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("referred_owner_account_id");

                    b.Property<Guid>("ReferrerOwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("referrer_owner_account_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReferredOwnerAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_referral_relationships_referred");

                    b.ToTable("referral_relationships", "accounts");
                });

            modelBuilder.Entity("Accounts.Domain.OwnerAccounts.OwnerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("account_name");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer")
                        .HasColumnName("account_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid>("PrimaryOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_owner_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryOwnerUserId")
                        .HasDatabaseName("ix_owner_accounts_primary_owner_user_id");

                    b.ToTable("owner_accounts", "accounts");
                });

            modelBuilder.Entity("Accounts.Domain.OwnerAccounts.OwnerAccountMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_membership_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId", "UserId")
                        .HasDatabaseName("ix_owner_account_memberships_account_user")
                        .HasFilter("status <> 3");

                    b.ToTable("owner_account_memberships", "accounts");
                });

            modelBuilder.Entity("Accounts.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<string>("BillingProviderCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("billing_provider_customer_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plan_code");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TrialEndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from_utc");

                    b.Property<DateTime>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_owner_account_active")
                        .HasFilter("status IN (1, 2)");

                    b.ToTable("subscriptions", "accounts");
                });

            modelBuilder.Entity("Accounts.Domain.Subscriptions.SubscriptionWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_event_id");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at_utc");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id");

                    b.HasIndex("ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscription_webhook_events_provider_event_id");

                    b.ToTable("subscription_webhook_events", "accounts");
                });

            modelBuilder.Entity("Accounts.Domain.OwnerAccounts.OwnerAccountMembership", b =>
                {
                    b.HasOne("Accounts.Domain.OwnerAccounts.OwnerAccount", null)
                        .WithMany("Memberships")
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounts.Domain.OwnerAccounts.OwnerAccount", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
