// <auto-generated>
//   Source: sync-contract/schemas/payloads/add_cost_entry.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record LocationItem(
    decimal Latitude,
    decimal Longitude,
    decimal AccuracyMeters,
    DateTime CapturedAtUtc,
    string Provider,
    string PermissionState,
    decimal? Altitude = null
);

public sealed record AddCostEntryPayload(
    Guid CostEntryId,
    Guid FarmId,
    /// <summary>Allowed values: "labour_payout", "labour_misc", "seeds", "fertilizer", "pesticide", "irrigation", "machinery_rent", "equipment", "fuel", "transport", "electricity", "packaging", "other".</summary>
    string CategoryId,
    string Description,
    decimal Amount,
    string CurrencyCode,
    DateOnly EntryDate,
    Guid? PlotId = null,
    Guid? CropCycleId = null,
    Guid? CreatedByUserId = null,
    LocationItem? Location = null
);
