// <auto-generated>
//   Source: sync-contract/schemas/payloads/add_cost_entry.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record AmountItem(
    int AmountMinor,
    // generator: unhandled zod typeName ZodLiteral — emitted as object
    object Currency
);

public sealed record AddCostEntryPayload(
    Guid CostEntryId,
    Guid FarmId,
    IReadOnlyList<Guid> PlotIds,
    string Category,
    AmountItem Amount,
    DateTime OccurredAt,
    string? Notes = null
);
