// <auto-generated>
//   Source: sync-contract/schemas/payloads/add_location.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record AddLocationPayload(
    decimal Latitude,
    decimal Longitude,
    decimal AccuracyMeters,
    DateTime CapturedAtUtc,
    string Provider,
    string PermissionState,
    decimal? Altitude = null
);
