// <auto-generated>
//   Source: sync-contract/schemas/payloads/add_log_task.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record AddLogTaskPayload(
    Guid DailyLogId,
    string ActivityType,
    Guid? LogTaskId = null,
    string? Notes = null,
    DateTime? OccurredAtUtc = null
);
