// <auto-generated>
//   Source: sync-contract/schemas/payloads/adopt_schedule.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record AdoptSchedulePayload(
    Guid FarmId,
    Guid PlotId,
    Guid CropCycleId,
    Guid ScheduleTemplateId,
    Guid ActorUserId,
    string? ActorRole = null,
    string? ClientCommandId = null,
    Guid? SubscriptionId = null
);
