// <auto-generated>
//   Source: sync-contract/schemas/payloads/allocate_global_expense.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record AllocationsItem(
    Guid PlotId,
    decimal Amount
);

public sealed record AllocateGlobalExpensePayload(
    Guid CostEntryId,
    string AllocationBasis,
    IReadOnlyList<AllocationsItem> Allocations,
    Guid? DayLedgerId = null,
    Guid? CreatedByUserId = null
);
