// <auto-generated>
//   Source: sync-contract/schemas/payloads/attendance_mark.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record AttendanceMarkPayload(
    Guid AttendanceMarkId,
    Guid FarmId,
    Guid FieldOperatorId,
    DateOnly WorkDate,
    /// <summary>Allowed values: "Full", "Half", "Absent".</summary>
    string? DayMark = null,
    /// <summary>Allowed values: "Worked", "NotWorked".</summary>
    string? NightMark = null,
    decimal? HoursWorked = null,
    decimal? ExtraHours = null,
    Guid? ResolvedLabourAssignmentId = null
);
