// <auto-generated>
//   Source: sync-contract/schemas/payloads/compliance_resolve.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record ComplianceResolvePayload(
    Guid SignalId,
    string? Note = null
);
