// <auto-generated>
//   Source: sync-contract/schemas/payloads/compliance_acknowledge.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record ComplianceAcknowledgePayload(
    Guid SignalId
);
