// <auto-generated>
//   Source: sync-contract/schemas/payloads/correct_cost_entry.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record CorrectCostEntryPayload(
    Guid CostEntryId,
    decimal CorrectedAmount,
    string CurrencyCode,
    string Reason,
    Guid? FinanceCorrectionId = null,
    Guid? CorrectedByUserId = null
);
