// <auto-generated>
//   Source: sync-contract/schemas/payloads/create_daily_log.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record LocationItem(
    decimal Latitude,
    decimal Longitude,
    decimal AccuracyMeters,
    DateTime CapturedAtUtc,
    string Provider,
    string PermissionState,
    decimal? Altitude = null
);

public sealed record CreateDailyLogPayload(
    Guid DailyLogId,
    Guid FarmId,
    Guid PlotId,
    Guid CropCycleId,
    DateOnly LogDate,
    Guid? OperatorUserId = null,
    LocationItem? Location = null
);
