// <auto-generated>
//   Source: sync-contract/schemas/payloads/create_attachment.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record CreateAttachmentPayload(
    Guid AttachmentId,
    Guid FarmId,
    Guid LinkedEntityId,
    string LinkedEntityType,
    string FileName,
    string MimeType,
    Guid? CreatedByUserId = null
);
