// <auto-generated>
//   Source: sync-contract/schemas/payloads/create_plot.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record CreatePlotPayload(
    Guid FarmId,
    string Name,
    decimal AreaInAcres,
    Guid? PlotId = null
);
