// <auto-generated>
//   Source: sync-contract/schemas/payloads/create_crop_cycle.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record CreateCropCyclePayload(
    Guid FarmId,
    Guid PlotId,
    string CropName,
    string Stage,
    DateOnly StartDate,
    Guid? CropCycleId = null,
    DateOnly? EndDate = null
);
