// <auto-generated>
//   Source: sync-contract/schemas/payloads/create_daily_log.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record LocationItem(
    decimal Latitude,
    decimal Longitude,
    decimal AccuracyMeters,
    DateTime CapturedAtUtc,
    string Provider,
    string PermissionState,
    decimal? Altitude = null
);

public sealed record WeatherStampItem(
    string TimestampLocal,
    string TimestampProvider,
    string Provider,
    decimal TempC,
    decimal Humidity,
    decimal WindKph,
    decimal PrecipMm,
    decimal CloudCoverPct,
    string ConditionText,
    string IconCode,
    decimal RainProbNext6h,
    Guid? PlotId = null,
    decimal? WindGustKph = null,
    decimal? SoilMoistureVolumetric0To10 = null,
    decimal? UvIndex = null,
    IReadOnlyList<string>? Alerts = null
);

public sealed record DisturbanceItem(
    string? Scope = null,
    string? Cause = null,
    string? Reason = null
);

public sealed record ManualDraftItem(
    // generator: ZodAny / ZodUnknown
    IReadOnlyList<object>? Labour = null,
    // generator: ZodAny / ZodUnknown
    IReadOnlyList<object>? Inputs = null,
    // generator: ZodAny / ZodUnknown
    IReadOnlyList<object>? Irrigation = null,
    // generator: ZodAny / ZodUnknown
    IReadOnlyList<object>? Observations = null,
    // generator: ZodAny / ZodUnknown
    IReadOnlyList<object>? PlannedTasks = null,
    // generator: ZodAny / ZodUnknown
    IReadOnlyList<object>? CropActivities = null,
    // generator: ZodAny / ZodUnknown
    IReadOnlyList<object>? Machinery = null,
    // generator: ZodAny / ZodUnknown
    IReadOnlyList<object>? ActivityExpenses = null,
    /// <summary>Allowed values: "WORK_RECORDED", "DISTURBANCE_RECORDED", "NO_WORK_PLANNED", "IRRELEVANT_INPUT".</summary>
    string? DayOutcome = null,
    DisturbanceItem? Disturbance = null
);

public sealed record CreateDailyLogPayload(
    Guid DailyLogId,
    Guid FarmId,
    Guid PlotId,
    Guid CropCycleId,
    DateOnly LogDate,
    Guid? OperatorUserId = null,
    LocationItem? Location = null,
    WeatherStampItem? WeatherStamp = null,
    Guid? SourceAiJobId = null,
    ManualDraftItem? ManualDraft = null
);
