// <auto-generated>
//   Source: sync-contract/schemas/payloads/jobcard_create.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record LineItemsItem(
    string ActivityType,
    decimal ExpectedHours,
    decimal RatePerHourAmount,
    string RatePerHourCurrencyCode,
    string? Notes = null
);

public sealed record JobCardCreatePayload(
    Guid FarmId,
    Guid PlotId,
    DateOnly PlannedDate,
    IReadOnlyList<LineItemsItem> LineItems,
    Guid? CropCycleId = null
);
