// <auto-generated>
//   Source: sync-contract/schemas/payloads/jobcard_settle.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record JobCardSettlePayload(
    Guid JobCardId,
    decimal ActualPayoutAmount,
    string ActualPayoutCurrencyCode,
    string? SettlementNote = null
);
