// <auto-generated>
//   Source: sync-contract/schemas/payloads/migrate_schedule.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record MigrateSchedulePayload(
    Guid FarmId,
    Guid PlotId,
    Guid CropCycleId,
    Guid NewScheduleTemplateId,
    /// <summary>Allowed values: "BetterFit", "WeatherShift", "SwitchedCropVariety", "OwnerDirective", "Other".</summary>
    string Reason,
    Guid ActorUserId,
    string? ReasonText = null,
    string? ActorRole = null,
    string? ClientCommandId = null,
    Guid? NewSubscriptionId = null,
    Guid? MigrationEventId = null
);
