// <auto-generated>
//   Source: sync-contract/schemas/payloads/plan_remove.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record RemovePlannedPayload(
    Guid FarmId,
    Guid PlotId,
    Guid CropCycleId,
    Guid PlannedActivityId,
    Guid ActorUserId,
    string? ActorRole = null,
    string? ClientCommandId = null
);
