// <auto-generated>
//   Source: sync-contract/schemas/payloads/set_price_config.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record SetPriceConfigPayload(
    string ItemName,
    decimal UnitPrice,
    string CurrencyCode,
    DateOnly EffectiveFrom,
    int Version,
    Guid? PriceConfigId = null,
    Guid? CreatedByUserId = null
);
