// <auto-generated>
//   Source: sync-contract/schemas/payloads/testinstance_reported.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record ResultsItem(
    string ParameterCode,
    string ParameterValue,
    string? Unit = null,
    decimal? ReferenceRangeLow = null,
    decimal? ReferenceRangeHigh = null
);

public sealed record TestInstanceReportedPayload(
    Guid TestInstanceId,
    IReadOnlyList<ResultsItem> Results,
    IReadOnlyList<Guid>? AttachmentIds = null,
    string? ClientCommandId = null
);
