// <auto-generated>
//   Source: sync-contract/schemas/payloads/testinstance_collected.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record TestInstanceCollectedPayload(
    Guid TestInstanceId
);
