// <auto-generated>
//   Source: sync-contract/schemas/payloads/verify_log.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record VerifyLogPayload(
    Guid DailyLogId,
    Guid? VerificationEventId = null,
    string? Status = null,
    string? TargetStatus = null,
    string? Reason = null,
    Guid? VerifiedByUserId = null
);
