// <auto-generated>
//   Source: sync-contract/schemas/payloads/verify_log_v2.zod.ts
//   Regenerate with: cd sync-contract && npm run generate:csharp
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace ShramSafal.Application.Contracts.Sync.Payloads;

public sealed record VerifyLogV2Payload(
    Guid LogId,
    Guid VerifierUserId,
    /// <summary>Allowed values: "confirm", "verify", "dispute", "request_correction".</summary>
    string Decision,
    DateTime DecidedAt,
    string? Reason = null
);
