// <auto-generated>
//   Source: sync-contract/schemas/mutation-types.json
//   Regenerate with: cd sync-contract && npm run generate
//   Last source version: 1.0.0 (2026-04-30)
// </auto-generated>

#nullable enable


using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace ShramSafal.Application.Contracts.Sync;

public static class SyncMutationCatalog
{
    public const string CreateFarm = "create_farm";
    public const string CreatePlot = "create_plot";
    public const string CreateCropCycle = "create_crop_cycle";
    public const string CreateDailyLog = "create_daily_log";
    public const string AddLogTask = "add_log_task";
    public const string VerifyLog = "verify_log";
    public const string VerifyLogV2 = "verify_log_v2";
    public const string AddCostEntry = "add_cost_entry";
    public const string CorrectCostEntry = "correct_cost_entry";
    public const string AllocateGlobalExpense = "allocate_global_expense";
    public const string SetPriceConfig = "set_price_config";
    public const string CreateAttachment = "create_attachment";
    public const string AddLocation = "add_location";
    public const string SchedulePublish = "schedule.publish";
    public const string ScheduleEdit = "schedule.edit";
    public const string ScheduleClone = "schedule.clone";
    public const string PlanAdd = "plan.add";
    public const string PlanOverride = "plan.override";
    public const string PlanRemove = "plan.remove";
    public const string AdoptSchedule = "adopt_schedule";
    public const string MigrateSchedule = "migrate_schedule";
    public const string AbandonSchedule = "abandon_schedule";
    public const string ComplianceAcknowledge = "compliance.acknowledge";
    public const string ComplianceResolve = "compliance.resolve";
    public const string TestinstanceCollected = "testinstance.collected";
    public const string TestinstanceReported = "testinstance.reported";
    public const string JobcardCreate = "jobcard.create";
    public const string JobcardAssign = "jobcard.assign";
    public const string JobcardStart = "jobcard.start";
    public const string JobcardComplete = "jobcard.complete";
    public const string JobcardSettle = "jobcard.settle";
    public const string JobcardCancel = "jobcard.cancel";

    public static readonly ImmutableArray<SyncMutationDescriptor> All = ImmutableArray.Create(
        new SyncMutationDescriptor(Name: "create_farm", OwnerAggregate: "Farm", SinceVersion: "0.1.0", PayloadSchema: "CreateFarm"),
        new SyncMutationDescriptor(Name: "create_plot", OwnerAggregate: "Plot", SinceVersion: "0.1.0", PayloadSchema: "CreatePlot"),
        new SyncMutationDescriptor(Name: "create_crop_cycle", OwnerAggregate: "CropCycle", SinceVersion: "0.1.0", PayloadSchema: "CreateCropCycle"),
        new SyncMutationDescriptor(Name: "create_daily_log", OwnerAggregate: "DailyLog", SinceVersion: "0.1.0", PayloadSchema: "CreateDailyLog"),
        new SyncMutationDescriptor(Name: "add_log_task", OwnerAggregate: "DailyLog", SinceVersion: "0.1.0", PayloadSchema: "AddLogTask"),
        new SyncMutationDescriptor(Name: "verify_log", OwnerAggregate: "DailyLog", SinceVersion: "0.1.0", PayloadSchema: "VerifyLog", DeprecatedBy: "verify_log_v2"),
        new SyncMutationDescriptor(Name: "verify_log_v2", OwnerAggregate: "DailyLog", SinceVersion: "0.7.0", PayloadSchema: "VerifyLogV2"),
        new SyncMutationDescriptor(Name: "add_cost_entry", OwnerAggregate: "CostEntry", SinceVersion: "0.2.0", PayloadSchema: "AddCostEntry"),
        new SyncMutationDescriptor(Name: "correct_cost_entry", OwnerAggregate: "CostEntry", SinceVersion: "0.5.0", PayloadSchema: "CorrectCostEntry"),
        new SyncMutationDescriptor(Name: "allocate_global_expense", OwnerAggregate: "CostEntry", SinceVersion: "0.5.0", PayloadSchema: "AllocateGlobalExpense"),
        new SyncMutationDescriptor(Name: "set_price_config", OwnerAggregate: "PriceConfig", SinceVersion: "0.6.0", PayloadSchema: "SetPriceConfig"),
        new SyncMutationDescriptor(Name: "create_attachment", OwnerAggregate: "Attachment", SinceVersion: "0.4.0", PayloadSchema: "CreateAttachment"),
        new SyncMutationDescriptor(Name: "add_location", OwnerAggregate: "DailyLog", SinceVersion: "0.6.0", PayloadSchema: "AddLocation"),
        new SyncMutationDescriptor(Name: "schedule.publish", OwnerAggregate: "ScheduleTemplate", SinceVersion: "0.8.0", PayloadSchema: "PublishSchedule"),
        new SyncMutationDescriptor(Name: "schedule.edit", OwnerAggregate: "ScheduleTemplate", SinceVersion: "0.8.0", PayloadSchema: "EditSchedule"),
        new SyncMutationDescriptor(Name: "schedule.clone", OwnerAggregate: "ScheduleTemplate", SinceVersion: "0.8.0", PayloadSchema: "CloneSchedule"),
        new SyncMutationDescriptor(Name: "plan.add", OwnerAggregate: "PlannedActivity", SinceVersion: "0.8.0", PayloadSchema: "AddPlanned"),
        new SyncMutationDescriptor(Name: "plan.override", OwnerAggregate: "PlannedActivity", SinceVersion: "0.8.0", PayloadSchema: "OverridePlanned"),
        new SyncMutationDescriptor(Name: "plan.remove", OwnerAggregate: "PlannedActivity", SinceVersion: "0.8.0", PayloadSchema: "RemovePlanned"),
        new SyncMutationDescriptor(Name: "adopt_schedule", OwnerAggregate: "PlannedActivity", SinceVersion: "0.9.0", PayloadSchema: "AdoptSchedule"),
        new SyncMutationDescriptor(Name: "migrate_schedule", OwnerAggregate: "PlannedActivity", SinceVersion: "0.9.0", PayloadSchema: "MigrateSchedule"),
        new SyncMutationDescriptor(Name: "abandon_schedule", OwnerAggregate: "PlannedActivity", SinceVersion: "0.9.0", PayloadSchema: "AbandonSchedule"),
        new SyncMutationDescriptor(Name: "compliance.acknowledge", OwnerAggregate: "ComplianceSignal", SinceVersion: "0.9.0", PayloadSchema: "ComplianceAcknowledge"),
        new SyncMutationDescriptor(Name: "compliance.resolve", OwnerAggregate: "ComplianceSignal", SinceVersion: "0.9.0", PayloadSchema: "ComplianceResolve"),
        new SyncMutationDescriptor(Name: "testinstance.collected", OwnerAggregate: "TestInstance", SinceVersion: "0.9.0", PayloadSchema: "TestInstanceCollected"),
        new SyncMutationDescriptor(Name: "testinstance.reported", OwnerAggregate: "TestInstance", SinceVersion: "0.9.0", PayloadSchema: "TestInstanceReported"),
        new SyncMutationDescriptor(Name: "jobcard.create", OwnerAggregate: "JobCard", SinceVersion: "1.0.0", PayloadSchema: "JobCardCreate"),
        new SyncMutationDescriptor(Name: "jobcard.assign", OwnerAggregate: "JobCard", SinceVersion: "1.0.0", PayloadSchema: "JobCardAssign"),
        new SyncMutationDescriptor(Name: "jobcard.start", OwnerAggregate: "JobCard", SinceVersion: "1.0.0", PayloadSchema: "JobCardStart"),
        new SyncMutationDescriptor(Name: "jobcard.complete", OwnerAggregate: "JobCard", SinceVersion: "1.0.0", PayloadSchema: "JobCardComplete"),
        new SyncMutationDescriptor(Name: "jobcard.settle", OwnerAggregate: "JobCard", SinceVersion: "1.0.0", PayloadSchema: "JobCardSettle"),
        new SyncMutationDescriptor(Name: "jobcard.cancel", OwnerAggregate: "JobCard", SinceVersion: "1.0.0", PayloadSchema: "JobCardCancel")
    );

    public static readonly ImmutableHashSet<string> Names =
        All.Select(m => m.Name).ToImmutableHashSet();

    public static bool IsKnown(string? name) => name is not null && Names.Contains(name);
}

public sealed record SyncMutationDescriptor(
    string Name,
    string OwnerAggregate,
    string SinceVersion,
    string PayloadSchema,
    string? DeprecatedBy = null);
