using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ShramSafal.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class FinanceV2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'ssf'
          AND table_name = 'cost_entries'
    ) THEN
        ALTER TABLE ssf.cost_entries
            ADD COLUMN IF NOT EXISTS is_flagged boolean NOT NULL DEFAULT FALSE;

        ALTER TABLE ssf.cost_entries
            ADD COLUMN IF NOT EXISTS flag_reason character varying(300);
    END IF;
END $$;
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS ssf.day_ledgers (
    id uuid PRIMARY KEY,
    farm_id uuid NOT NULL,
    date_key date NOT NULL,
    global_expense_ids uuid[] NOT NULL DEFAULT '{}',
    allocation_strategy character varying(32) NOT NULL,
    total_global_cost numeric(18,2) NOT NULL,
    created_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_day_ledgers_farm_id_date_key
    ON ssf.day_ledgers (farm_id, date_key);

CREATE TABLE IF NOT EXISTS ssf.day_ledger_plot_allocations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_ledger_id uuid NOT NULL REFERENCES ssf.day_ledgers(id) ON DELETE CASCADE,
    plot_id uuid NOT NULL,
    crop_cycle_id uuid NOT NULL,
    allocation_percent numeric(8,2) NOT NULL,
    allocated_amount numeric(18,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_day_ledger_plot_allocations_day_ledger_id
    ON ssf.day_ledger_plot_allocations(day_ledger_id);
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DROP TABLE IF EXISTS ssf.day_ledger_plot_allocations;
DROP TABLE IF EXISTS ssf.day_ledgers;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'ssf'
          AND table_name = 'cost_entries'
    ) THEN
        ALTER TABLE ssf.cost_entries DROP COLUMN IF EXISTS flag_reason;
        ALTER TABLE ssf.cost_entries DROP COLUMN IF EXISTS is_flagged;
    END IF;
END $$;
""");
        }
    }
}
