// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShramSafal.Infrastructure.Persistence;

#nullable disable

namespace ShramSafal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShramSafalDbContext))]
    [Migration("20260418144043_AddFarmOwnerAccountIdNullable")]
    partial class AddFarmOwnerAccountIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ssf")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShramSafal.Domain.AI.AiJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("InputContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_content_hash");

                    b.Property<int?>("InputRawDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("input_raw_duration_ms");

                    b.Property<string>("InputSessionMetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_session_metadata_json");

                    b.Property<int?>("InputSpeechDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("input_speech_duration_ms");

                    b.Property<string>("InputStoragePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("input_storage_path");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("NormalizedResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("normalized_result_json");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation_type");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("total_attempts");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("FarmId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("ai_jobs", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.AI.AiJobAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_job_id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at_utc");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence_score");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<decimal?>("EstimatedCostUnits")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("estimated_cost_units");

                    b.Property<string>("FailureClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_class");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("RawProviderResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_provider_response");

                    b.Property<string>("RequestPayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_payload_hash");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.HasKey("Id");

                    b.HasIndex("AiJobId");

                    b.HasIndex("AttemptedAtUtc");

                    b.HasIndex("Provider");

                    b.HasIndex("AiJobId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("ai_job_attempts", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.AI.AiProviderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CircuitBreakerResetSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("circuit_breaker_reset_seconds");

                    b.Property<int>("CircuitBreakerThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("circuit_breaker_threshold");

                    b.Property<string>("DefaultProvider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("default_provider");

                    b.Property<bool>("FallbackEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("fallback_enabled");

                    b.Property<bool>("IsAiProcessingDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ai_processing_disabled");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("PattiProvider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("patti_provider");

                    b.Property<decimal>("ReceiptConfidenceThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("receipt_confidence_threshold");

                    b.Property<string>("ReceiptProvider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("receipt_provider");

                    b.Property<decimal>("VoiceConfidenceThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("voice_confidence_threshold");

                    b.Property<string>("VoiceProvider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("voice_provider");

                    b.HasKey("Id");

                    b.ToTable("ai_provider_configs", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.AI.DocumentExtractionSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_type");

                    b.Property<Guid?>("DraftAiJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_ai_job_id");

                    b.Property<decimal>("DraftConfidence")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("draft_confidence");

                    b.Property<string>("DraftProvider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("draft_provider");

                    b.Property<string>("DraftResultJson")
                        .HasColumnType("text")
                        .HasColumnName("draft_result_json");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("InputImagePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("input_image_path");

                    b.Property<string>("InputMimeType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("input_mime_type");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("VerificationAiJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("verification_ai_job_id");

                    b.Property<string>("VerificationProvider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("verification_provider");

                    b.Property<decimal?>("VerifiedConfidence")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("verified_confidence");

                    b.Property<string>("VerifiedResultJson")
                        .HasColumnType("text")
                        .HasColumnName("verified_result_json");

                    b.HasKey("Id");

                    b.HasIndex("FarmId", "Status");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("document_extraction_sessions", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Attachments.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("FinalizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at_utc");

                    b.Property<Guid>("LinkedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_entity_id");

                    b.Property<string>("LinkedEntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("linked_entity_type");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("local_path");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("mime_type");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedAtUtc");

                    b.HasIndex("FarmId", "CreatedAtUtc");

                    b.HasIndex("LinkedEntityType", "LinkedEntityId");

                    b.ToTable("attachments", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("actor_role");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("ClientCommandId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("client_command_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("FarmId", "OccurredAtUtc");

                    b.ToTable("audit_events", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Crops.CropCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("crop_name");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("stage");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedAtUtc");

                    b.HasIndex("FarmId", "PlotId", "StartDate");

                    b.ToTable("crop_cycles", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Farms.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FarmCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("farm_code");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id");

                    b.HasIndex("FarmCode")
                        .IsUnique()
                        .HasDatabaseName("ux_farms_farm_code")
                        .HasFilter("farm_code IS NOT NULL");

                    b.HasIndex("ModifiedAtUtc");

                    b.HasIndex("OwnerAccountId")
                        .HasDatabaseName("ix_farms_owner_account_id");

                    b.ToTable("farms", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Farms.FarmMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTime?>("ExitedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exited_at_utc");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at_utc");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<int>("JoinedVia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("joined_via");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("UserId");

                    b.HasIndex("FarmId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_farm_memberships_farm_user_nonterminal")
                        .HasFilter("status NOT IN (5, 6)");

                    b.ToTable("farm_memberships", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Farms.Plot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaInAcres")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("area_in_acres");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedAtUtc");

                    b.HasIndex("FarmId", "Name");

                    b.ToTable("plots", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Finance.CostEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CropCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_cycle_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("FlagReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("flag_reason");

                    b.Property<bool>("IsCorrected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_corrected");

                    b.Property<bool>("IsFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_flagged");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CropCycleId");

                    b.HasIndex("FarmId");

                    b.HasIndex("ModifiedAtUtc");

                    b.HasIndex("PlotId");

                    b.HasIndex("FarmId", "EntryDate");

                    b.ToTable("cost_entries", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Finance.DayLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AllocationBasis")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("allocation_basis");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<DateOnly>("LedgerDate")
                        .HasColumnType("date")
                        .HasColumnName("ledger_date");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid>("SourceCostEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_cost_entry_id");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedAtUtc");

                    b.HasIndex("SourceCostEntryId")
                        .IsUnique();

                    b.HasIndex("FarmId", "LedgerDate");

                    b.ToTable("day_ledgers", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Finance.FinanceCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CorrectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("corrected_amount");

                    b.Property<DateTime>("CorrectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("corrected_at_utc");

                    b.Property<Guid>("CorrectedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("corrected_by_user_id");

                    b.Property<Guid>("CostEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_entry_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency_code");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<decimal>("OriginalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("original_amount");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedAtUtc");

                    b.HasIndex("CostEntryId", "CorrectedAtUtc");

                    b.ToTable("finance_corrections", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Finance.PriceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("item_name");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedAtUtc");

                    b.HasIndex("ItemName", "Version")
                        .IsUnique();

                    b.ToTable("price_configs", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CropCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_cycle_id");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_user_id");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.HasKey("Id");

                    b.HasIndex("CropCycleId");

                    b.HasIndex("FarmId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("ModifiedAtUtc");

                    b.HasIndex("OperatorUserId");

                    b.HasIndex("FarmId", "LogDate");

                    b.ToTable("daily_logs", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.LogTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("activity_type");

                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_log_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId", "OccurredAtUtc");

                    b.ToTable("log_tasks", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.VerificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_log_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Reason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId", "OccurredAtUtc");

                    b.ToTable("verification_events", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Planning.PlannedActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("activity_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CropCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_cycle_id");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_date");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("stage");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedAtUtc");

                    b.HasIndex("CropCycleId", "PlannedDate");

                    b.ToTable("planned_activities", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Planning.ScheduleTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("stage");

                    b.HasKey("Id");

                    b.ToTable("schedule_templates", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Planning.TemplateActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("activity_name");

                    b.Property<int>("OffsetDays")
                        .HasColumnType("integer")
                        .HasColumnName("offset_days");

                    b.Property<Guid>("ScheduleTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_template_id");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleTemplateId");

                    b.ToTable("template_activities", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Infrastructure.Persistence.SyncMutationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientRequestId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("client_request_id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_id");

                    b.Property<string>("MutationType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("mutation_type");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("ResponsePayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_payload_json");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ClientRequestId")
                        .IsUnique();

                    b.ToTable("sync_mutations", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.AI.AiJobAttempt", b =>
                {
                    b.HasOne("ShramSafal.Domain.AI.AiJob", null)
                        .WithMany("Attempts")
                        .HasForeignKey("AiJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShramSafal.Domain.Finance.CostEntry", b =>
                {
                    b.OwnsOne("ShramSafal.Domain.Location.LocationSnapshot", "Location", b1 =>
                        {
                            b1.Property<Guid>("CostEntryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AccuracyMeters")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("location_accuracy_meters");

                            b1.Property<decimal?>("Altitude")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("location_altitude");

                            b1.Property<DateTime>("CapturedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("location_captured_at_utc");

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(10, 7)
                                .HasColumnType("numeric(10,7)")
                                .HasColumnName("location_latitude");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(10, 7)
                                .HasColumnType("numeric(10,7)")
                                .HasColumnName("location_longitude");

                            b1.Property<string>("PermissionState")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("location_permission_state");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("location_provider");

                            b1.HasKey("CostEntryId");

                            b1.ToTable("cost_entries", "ssf");

                            b1.WithOwner()
                                .HasForeignKey("CostEntryId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ShramSafal.Domain.Finance.DayLedger", b =>
                {
                    b.OwnsMany("ShramSafal.Domain.Finance.DayLedgerAllocation", "Allocations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("AllocatedAmount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("allocated_amount");

                            b1.Property<DateTime>("AllocatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("allocated_at_utc");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("currency_code");

                            b1.Property<Guid>("PlotId")
                                .HasColumnType("uuid")
                                .HasColumnName("plot_id");

                            b1.Property<Guid>("day_ledger_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("AllocatedAtUtc");

                            b1.HasIndex("PlotId");

                            b1.HasIndex("day_ledger_id");

                            b1.ToTable("day_ledger_allocations", "ssf");

                            b1.WithOwner()
                                .HasForeignKey("day_ledger_id");
                        });

                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.DailyLog", b =>
                {
                    b.OwnsOne("ShramSafal.Domain.Location.LocationSnapshot", "Location", b1 =>
                        {
                            b1.Property<Guid>("DailyLogId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AccuracyMeters")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("location_accuracy_meters");

                            b1.Property<decimal?>("Altitude")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("location_altitude");

                            b1.Property<DateTime>("CapturedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("location_captured_at_utc");

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(10, 7)
                                .HasColumnType("numeric(10,7)")
                                .HasColumnName("location_latitude");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(10, 7)
                                .HasColumnType("numeric(10,7)")
                                .HasColumnName("location_longitude");

                            b1.Property<string>("PermissionState")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("location_permission_state");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("location_provider");

                            b1.HasKey("DailyLogId");

                            b1.ToTable("daily_logs", "ssf");

                            b1.WithOwner()
                                .HasForeignKey("DailyLogId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.LogTask", b =>
                {
                    b.HasOne("ShramSafal.Domain.Logs.DailyLog", null)
                        .WithMany("Tasks")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.VerificationEvent", b =>
                {
                    b.HasOne("ShramSafal.Domain.Logs.DailyLog", null)
                        .WithMany("VerificationEvents")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShramSafal.Domain.Planning.TemplateActivity", b =>
                {
                    b.HasOne("ShramSafal.Domain.Planning.ScheduleTemplate", null)
                        .WithMany("Activities")
                        .HasForeignKey("ScheduleTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShramSafal.Domain.AI.AiJob", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.DailyLog", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("VerificationEvents");
                });

            modelBuilder.Entity("ShramSafal.Domain.Planning.ScheduleTemplate", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
