// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShramSafal.Infrastructure.Persistence;

#nullable disable

namespace ShramSafal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShramSafalDbContext))]
    partial class ShramSafalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ssf")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShramSafal.Domain.Crops.CropCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("crop_name");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("stage");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("FarmId", "PlotId", "StartDate");

                    b.ToTable("crop_cycles", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Farms.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id");

                    b.ToTable("farms", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Farms.Plot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaInAcres")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("area_in_acres");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("FarmId", "Name");

                    b.ToTable("plots", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Finance.CostEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CropCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_cycle_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("FlagReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("flag_reason");

                    b.Property<bool>("IsCorrected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_corrected");

                    b.Property<bool>("IsFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_flagged");

                    b.Property<Guid?>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.HasKey("Id");

                    b.HasIndex("EntryDate", "FarmId");

                    b.ToTable("cost_entries", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Finance.DayLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AllocationStrategy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("allocation_strategy");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("DateKey")
                        .HasColumnType("date")
                        .HasColumnName("date_key");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.PrimitiveCollection<List<Guid>>("GlobalExpenseIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("global_expense_ids");

                    b.Property<decimal>("TotalGlobalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_global_cost");

                    b.HasKey("Id");

                    b.HasIndex("FarmId", "DateKey")
                        .IsUnique();

                    b.ToTable("day_ledgers", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Finance.FinanceCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CorrectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("corrected_amount");

                    b.Property<DateTime>("CorrectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("corrected_at_utc");

                    b.Property<Guid>("CorrectedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("corrected_by_user_id");

                    b.Property<Guid>("CostEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_entry_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("OriginalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("original_amount");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("CostEntryId", "CorrectedAtUtc");

                    b.ToTable("finance_corrections", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Finance.PriceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("item_name");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ItemName", "Version")
                        .IsUnique();

                    b.ToTable("price_configs", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CropCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_cycle_id");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_user_id");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plot_id");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.ToTable("daily_logs", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.LogTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("activity_type");

                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_log_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId", "OccurredAtUtc");

                    b.ToTable("log_tasks", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.VerificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_log_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Reason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId", "OccurredAtUtc");

                    b.ToTable("verification_events", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Planning.PlannedActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("activity_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CropCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_cycle_id");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_date");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("stage");

                    b.HasKey("Id");

                    b.HasIndex("CropCycleId", "PlannedDate");

                    b.ToTable("planned_activities", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Planning.ScheduleTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("stage");

                    b.HasKey("Id");

                    b.ToTable("schedule_templates", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Planning.TemplateActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("activity_name");

                    b.Property<int>("OffsetDays")
                        .HasColumnType("integer")
                        .HasColumnName("offset_days");

                    b.Property<Guid>("ScheduleTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_template_id");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleTemplateId");

                    b.ToTable("template_activities", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Infrastructure.Persistence.SyncMutationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientRequestId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("client_request_id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_id");

                    b.Property<string>("MutationType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("mutation_type");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("ResponsePayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_payload_json");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ClientRequestId")
                        .IsUnique();

                    b.ToTable("sync_mutations", "ssf");
                });

            modelBuilder.Entity("ShramSafal.Domain.Finance.DayLedger", b =>
                {
                    b.OwnsMany("ShramSafal.Domain.Finance.PlotAllocation", "PlotAllocations", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<decimal>("AllocatedAmount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("allocated_amount");

                            b1.Property<decimal>("AllocationPercent")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("allocation_percent");

                            b1.Property<Guid>("CropCycleId")
                                .HasColumnType("uuid")
                                .HasColumnName("crop_cycle_id");

                            b1.Property<Guid>("PlotId")
                                .HasColumnType("uuid")
                                .HasColumnName("plot_id");

                            b1.Property<Guid>("day_ledger_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("day_ledger_id");

                            b1.ToTable("day_ledger_plot_allocations", "ssf");

                            b1.WithOwner()
                                .HasForeignKey("day_ledger_id");
                        });

                    b.Navigation("PlotAllocations");
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.LogTask", b =>
                {
                    b.HasOne("ShramSafal.Domain.Logs.DailyLog", null)
                        .WithMany("Tasks")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.VerificationEvent", b =>
                {
                    b.HasOne("ShramSafal.Domain.Logs.DailyLog", null)
                        .WithMany("VerificationEvents")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShramSafal.Domain.Planning.TemplateActivity", b =>
                {
                    b.HasOne("ShramSafal.Domain.Planning.ScheduleTemplate", null)
                        .WithMany("Activities")
                        .HasForeignKey("ScheduleTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShramSafal.Domain.Logs.DailyLog", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("VerificationEvents");
                });

            modelBuilder.Entity("ShramSafal.Domain.Planning.ScheduleTemplate", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
