#!/usr/bin/env node
// sync-contract/scripts/generate.mjs
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const json = JSON.parse(await readFile(new URL('../schemas/mutation-types.json', import.meta.url), 'utf8'));
const HEADER_TS = `// AUTO-GENERATED by sync-contract/scripts/generate.mjs
// Do NOT hand-edit. Source: sync-contract/schemas/mutation-types.json
// Regenerate with: cd sync-contract && npm run generate
// Last source version: ${json.version} (${json.lastUpdated})\n\n`;

const HEADER_CS = `// <auto-generated>
//   Source: sync-contract/schemas/mutation-types.json
//   Regenerate with: cd sync-contract && npm run generate
//   Last source version: ${json.version} (${json.lastUpdated})
// </auto-generated>

#nullable enable

`;

// ---------- TS output ----------
const tsLines = [];
tsLines.push(HEADER_TS);
tsLines.push("export const SYNC_MUTATION_TYPES = [");
for (const m of json.mutationTypes) {
  tsLines.push(`  ${JSON.stringify(m.name)},`);
}
tsLines.push("] as const;\n");
tsLines.push("export type SyncMutationType = typeof SYNC_MUTATION_TYPES[number];\n");
tsLines.push("export const SYNC_MUTATION_SET: ReadonlySet<SyncMutationType> = new Set(SYNC_MUTATION_TYPES);\n");
tsLines.push("export interface SyncMutationDescriptor {");
tsLines.push("  readonly name: SyncMutationType;");
tsLines.push("  readonly ownerAggregate: string;");
tsLines.push("  readonly sinceVersion: string;");
tsLines.push("  readonly payloadSchema: string;");
tsLines.push("  readonly deprecatedBy?: SyncMutationType;");
tsLines.push("}\n");
tsLines.push("export const SYNC_MUTATION_CATALOG: Readonly<Record<SyncMutationType, SyncMutationDescriptor>> = Object.freeze({");
for (const m of json.mutationTypes) {
  const dep = m.deprecatedBy ? `, deprecatedBy: ${JSON.stringify(m.deprecatedBy)}` : '';
  tsLines.push(`  ${JSON.stringify(m.name)}: { name: ${JSON.stringify(m.name)}, ownerAggregate: ${JSON.stringify(m.ownerAggregate)}, sinceVersion: ${JSON.stringify(m.sinceVersion)}, payloadSchema: ${JSON.stringify(m.payloadSchema)}${dep} },`);
}
tsLines.push("});\n");
tsLines.push("export function isSyncMutationType(value: string): value is SyncMutationType {");
tsLines.push("  return SYNC_MUTATION_SET.has(value as SyncMutationType);");
tsLines.push("}\n");

const tsOutPath = fileURLToPath(new URL('../../src/clients/mobile-web/src/infrastructure/sync/SyncMutationCatalog.ts', import.meta.url));
await mkdir(dirname(tsOutPath), { recursive: true });
await writeFile(tsOutPath, tsLines.join('\n'), 'utf8');

// ---------- C# output ----------
const csLines = [];
csLines.push(HEADER_CS);
csLines.push("using System.Collections.Generic;");
csLines.push("using System.Collections.Immutable;");
csLines.push("using System.Linq;");
csLines.push("");
csLines.push("namespace ShramSafal.Application.Contracts.Sync;");
csLines.push("");
csLines.push("public static class SyncMutationCatalog");
csLines.push("{");
for (const m of json.mutationTypes) {
  const constName = m.name
    .split(/[._]/)
    .map(w => w[0].toUpperCase() + w.slice(1))
    .join('');
  csLines.push(`    public const string ${constName} = ${JSON.stringify(m.name)};`);
}
csLines.push("");
csLines.push("    public static readonly ImmutableArray<SyncMutationDescriptor> All = ImmutableArray.Create(");
const descriptorLines = json.mutationTypes.map((m) => {
  const dep = m.deprecatedBy ? `, DeprecatedBy: ${JSON.stringify(m.deprecatedBy)}` : '';
  return `        new SyncMutationDescriptor(Name: ${JSON.stringify(m.name)}, OwnerAggregate: ${JSON.stringify(m.ownerAggregate)}, SinceVersion: ${JSON.stringify(m.sinceVersion)}, PayloadSchema: ${JSON.stringify(m.payloadSchema)}${dep})`;
});
csLines.push(descriptorLines.join(',\n'));
csLines.push("    );");
csLines.push("");
csLines.push("    public static readonly ImmutableHashSet<string> Names =");
csLines.push("        All.Select(m => m.Name).ToImmutableHashSet();");
csLines.push("");
csLines.push("    public static bool IsKnown(string? name) => name is not null && Names.Contains(name);");
csLines.push("}");
csLines.push("");
csLines.push("public sealed record SyncMutationDescriptor(");
csLines.push("    string Name,");
csLines.push("    string OwnerAggregate,");
csLines.push("    string SinceVersion,");
csLines.push("    string PayloadSchema,");
csLines.push("    string? DeprecatedBy = null);");
csLines.push("");

const csOutPath = fileURLToPath(new URL('../../src/apps/ShramSafal/ShramSafal.Application/Contracts/Sync/SyncMutationCatalog.cs', import.meta.url));
await mkdir(dirname(csOutPath), { recursive: true });
await writeFile(csOutPath, csLines.join('\n'), 'utf8');

console.log(`Wrote: ${tsOutPath}`);
console.log(`Wrote: ${csOutPath}`);
console.log(`OK — generated ${json.mutationTypes.length} mutations across TS + C#.`);
