// <auto-generated />
using System;
using AgriSync.BuildingBlocks.Analytics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgriSync.Bootstrapper.Migrations.Analytics
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260420030000_Phase_OpsObservability")]
    partial class Phase_OpsObservability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analytics")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgriSync.BuildingBlocks.Analytics.AnalyticsEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_role");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime?>("DeviceOccurredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("device_occurred_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("OwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.Property<string>("PropsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("props")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("v1")
                        .HasColumnName("schema_version");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("trigger");

                    b.HasKey("EventId");

                    b.HasIndex("ActorUserId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_analytics_events_actor_time")
                        .HasFilter("\"actor_user_id\" IS NOT NULL");

                    b.HasIndex("EventType", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_analytics_events_type_time");

                    b.HasIndex("FarmId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_analytics_events_farm_time")
                        .HasFilter("\"farm_id\" IS NOT NULL");

                    b.HasIndex("OwnerAccountId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_analytics_events_account_time")
                        .HasFilter("\"owner_account_id\" IS NOT NULL");

                    b.ToTable("events", "analytics");
                });
#pragma warning restore 612, 618
        }
    }
}
